# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  all-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      CREDENTIALS: ${{ secrets.CREDENTIALS }}
      
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Check env
      run: echo '${{ env.BASE_URL }}'
        
    - name: Install deps
      run: npm ci
    
    - name: Run tests
      run: npm test
      continue-on-error: true
      
    - name: Create allure report
      run: allure generate
      continue-on-error: true

    - name: Upload jest report
      uses: actions/upload-artifact@v3
      with:
        name: report
        if-no-files-found: error
        path: ./jest-html-report

    - name: Upload allure report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        if-no-files-found: error
        path: ./allure-report
    

