# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  all-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      TEST_LOGIN: ${{ secrets.TEST_LOGIN }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install deps
      run: npm ci
    
    - name: Run tests
      run: npm run test
      continue-on-error: true

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: test-results
        only-summary: 'true'
        path: junit-reports/jest-*.xml    # Path to test results
        reporter: jest-junit        # Format of test results
      continue-on-error: true
      # token: ${{ secrets.TOKEN }}

    # - name: Upload jest report
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: report
    #     if-no-files-found: error
    #     path: ./jest-html-report
    #   continue-on-error: true

    - name: Create allure report
      run: npm run report
      continue-on-error: true
    

    - name: Upload allure report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        if-no-files-found: error
        path: ./allure-report
      continue-on-error: true

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: allure-report
        clean: true
        token: ${{ secrets.TOKEN }}
      continue-on-error: true


    - name: Send telegram notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.actor }} created commit:
          Commit message: ${{ github.event.commits[0].message }}
          Repository: ${{ github.repository }}
          Commit: https://github.com/${{ github.repository }}/commit/${{github.sha}}
          Run:  https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

          Check allure test report: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/
      continue-on-error: true


